apiVersion: upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: {{ .Values.providers.aws.providerConfig.name }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    {{- include "cloud-providers.labels" . | nindent 4 }}
spec:
  credentials:
    source: {{ .Values.providers.aws.providerConfig.credentials.source }}
    {{- if eq .Values.providers.aws.providerConfig.credentials.source "Secret" }}
    secretRef:
      namespace: {{ .Values.providers.aws.providerConfig.credentials.secretRef.namespace }}
      name: {{ .Values.providers.aws.providerConfig.credentials.secretRef.name }}
      key: {{ .Values.providers.aws.providerConfig.credentials.secretRef.key }}
    {{- end }}
  {{- if .Values.providers.aws.providerConfig.defaultRegion }}
  defaultRegion: {{ .Values.providers.aws.providerConfig.defaultRegion }}
  {{- end }}
