{{- if and (empty .Values.providers.aws.providerConfig.existingSecret.name) (or .Values.providers.aws.providerConfig.credentials.accessKeyId .Values.providers.aws.providerConfig.credentials.secretAccessKey) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloud-providers.fullname" . }}-aws-creds
  namespace: crossplane-system
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    {{- include "cloud-providers.labels" . | nindent 4 }}
type: Opaque
data:
  creds: {{ include "cloud-providers.awsCredentials" . | b64enc }}
{{- end }}
