apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cloud-providers.fullname" . }}-sa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloud-providers.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crossplane-view
  labels:
    {{- include "cloud-providers.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crossplane-view
subjects:
- kind: ServiceAccount
  name: {{ include "cloud-providers.fullname" . }}-sa
  namespace: {{ .Release.Namespace }}
