# Default values for cloud-providers
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

# AWS Provider Configuration
providers:
  registry: "xpkg.crossplane.io"
  pullPolicy: ""
  packagePullSecrets: []
  serviceAccountName: ""

  aws:
    version: "v1.21.1"
    packages:
      s3: "crossplane-contrib/provider-aws-s3"
      rds: "crossplane-contrib/provider-aws-rds"
    waitJob:
      serviceAccountName: ""
    
    # AWS Provider Config
    providerConfig:
      name: "default"
      # Default AWS region
      defaultRegion: us-east-1
      
      # AWS credentials configuration
      # Option 1: Use existing secret (set existingSecret values)
      existingSecret:
        namespace: crossplane-system
        name: aws-creds
        key: creds
      
      # Option 2: Create new secret (leave existingSecret empty and set credentials)
      credentials:
        accessKeyId: ""
        secretAccessKey: ""
        # Optional session token
        sessionToken: ""
