# Default values for cloud-providers
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

# AWS Provider Configuration
providers:
  registry: "xpkg.crossplane.io"
  pullPolicy: ""
  packagePullSecrets: []
  serviceAccountName: ""

  aws:
    version: "v1.21.1"
    packages:
      s3: "crossplane-contrib/provider-aws-s3"
      rds: "crossplane-contrib/provider-aws-rds"
    waitJob:
      serviceAccountName: ""
    
    # AWS Provider Config
    providerConfig:
      name: "default"
      # AWS credentials source
      credentials:
        source: Secret
        secretRef:
          namespace: crossplane-system
          name: aws-creds
          key: creds
      # Default AWS region
      defaultRegion: us-east-1
