apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: cloud-resources
spec:
  # chart identifies a matching chart from a .tgz
  chart:
    name: cloud-resources
    chartVersion: 0.1.0

  weight: 100

  # values are used in the customer environment, as a pre-render step
  # these values will be supplied to helm template
  values: 
    s3:
      enabled: true
      bucketName: '{{repl LicenseFieldValue "appSlug"}}-{{repl LicenseFieldValue "customerName" | lower | nospace}}'
    rds:
      enabled: true
      instanceName: '{{repl LicenseFieldValue "appSlug"}}-{{repl LicenseFieldValue "customerName" | lower | nospace}}'

  optionalValues:
    # AWS_PROFILE=${AWS_PROFILE:=default} # retrieve profile's credentials, save it under 'default' profile, and base64 encode it
    # BASE64ENCODED_AWS_ACCOUNT_CREDS=$(echo "[default]\naws_access_key_id = $(aws configure get aws_access_key_id --profile $AWS_PROFILE)\naws_secret_access_key = $(aws configure get aws_secret_access_key --profile $AWS_PROFILE)" | base64  | tr -d "\n")
    # cat secret.yaml | sed "s/<REPLACEME>/${BASE64ENCODED_AWS_ACCOUNT_CREDS}/g" | kubectl apply -f -
    - when: '{{repl ConfigOptionEquals "cloud" "aws"}}'
      recursiveMerge: true
      values:
        provider:
          aws:
            credentials: |
              [default]
              aws_access_key_id = {{repl ConfigOption "aws_access_key_id"}} 
              aws_secret_access_key = {{repl ConfigOption "aws_secret_access_key"}}
