apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: cloud-providers
spec:
  # chart identifies a matching chart from a .tgz
  chart:
    name: cloud-providers
    chartVersion: 0.0.1
  weight: -10

  helmUpgradeFlags:
    - --wait
 
  # values are used in the customer environment, as a pre-render step
  # these values will be supplied to helm template
  values: 
    providers:
      aws:
        waitJob:
          serviceAccountName: kotsadm
